### PR TITLE
Backport ScrollItemScaling and WheelScrollDirection config options

### PR DESCRIPTION
**Pull request by unilock**
ScrollItemScaling allows either transferring an amount of items proportional to the scrolling speed *(EDIT: as reported by the mouse)*, or always transferring *only one* item per scroll event (which is useful on macOS).  
Originally introduced in Mouse Tweaks for 1.12.1.  
https://github.com/YaLTeR/MouseTweaks/commit/c980bc11b6218b2371ebf591c3cdef548fd2899e

WheelScrollDirection allows inverting the direction in which items are transferred between inventories when scrolling, and/or choosing a direction based on whether the target inventory (receiving items) is above or below the source inventory (sending items).  
Originally introduced in Mouse Tweaks for 1.10.2, with inventory position-aware transferring being added during 1.12.1, and inverted inventory position-aware transferring being added at the same time as ScrollItemScaling.  
https://github.com/YaLTeR/MouseTweaks/commit/f67841317242f942b661c3a82bfdf495402a9b57, https://github.com/YaLTeR/MouseTweaks/commit/60fb17e9efb2748ada7766d348f483fbef925d44, https://github.com/YaLTeR/MouseTweaks/commit/c980bc11b6218b2371ebf591c3cdef548fd2899e

For reference:
```
ScrollItemScaling.PROPORTIONAL = 0
ScrollItemScaling.ALWAYS_ONE = 1

WheelScrollDirection.NORMAL = 0
WheelScrollDirection.INVERTED = 1
WheelScrollDirection.INVENTORY_POSITION_AWARE = 2
WheelScrollDirection.INVENTORY_POSITION_AWARE_INVERTED = 3
```
(should these be put in proper enums?)

### CODE REVIEW

**Comment by unilock** [comment]
"Inventory position aware" scrolling seems to freeze the game sometimes. Not sure what the issue could be yet.

**Comment by wlhlm** [comment]
@unilock 

> "Inventory position aware" scrolling seems to freeze the game sometimes. Not sure what the issue could be yet.

Are you still investigating this?

**Comment by unilock** [comment]
I was able to reliably reproduce the freeze by attempting to scroll cobblestone into a furnace that already had a full stack of cobblestone in both its input and fuel slots. Putting a `!` where it was missing seems to have fixed it. Oops.

With that, this should now be ready to merge.

**Comment by wlhlm** [comment]
I've tried to test proportional scroll scaling in game, but it seems to be doing nothing.

`ScrollItemScaling=0` is set in the config

It seems to always transfer about the same amount, no matter the speed. I'm using a normal mouse. What I did was, transfer items from one inventory into the other with a single quick 'flick' of my finger over the scroll wheel to transfer from the source slot to the target slot and then do the reverse, but much slower (so in theory that should leave some items in the target slot since the scroll speed for transferring back from target slot to source slot is lower). With my mouse that's about 8 'notches' and indeed it transfers that amount of items between inventories, regardless of scroll speed.

So either this doesn't do anything, or the scaling is too low to be noticeable with a regular desktop mouse. Or maybe I'm holding it wrong...

Also, is there any place these options are documented outside of the reading the source code? For example how are people supposed to know the valid options for `WheelScrollDirection`?

**Comment by Dream-Master** [comment]
@unilock

**Comment by unilock** [comment]
@wlhlm
> I've tried to test proportional scroll scaling in game, but it seems to be doing nothing.

If I set `ScrollItemScaling=0`, the mod moves 3 items per "scroll wheel notch" on my Mac. Enabling the setting makes it only transfer 1 item, as intended.  
If you experience the same behavior on the official version of the mod, then that's probably outside the scope of this PR.

> Also, is there any place these options are documented outside of the reading the source code? For example how are people supposed to know the valid options for `WheelScrollDirection`?

The official mod has that info on its CurseForge listing (well, most of it - I guess it's (very) outdated). More accurately, it has an in-game configuration UI - but that seemed like a bit much to implement to me.  
If you'd like, I can edit the README.md with info on the config options.

@Dream-Master
> @unilock

Thanks, but I get GitHub notifications already XP

**Comment by wlhlm** [comment]
> If I set ScrollItemScaling=0, the mod moves 3 items per "scroll wheel notch" on my Mac. Enabling the setting makes it only transfer 1 item, as intended.
>If you experience the same behavior on the official version of the mod, then that's probably outside the scope of this PR.

Alright, I'd guess you wouldn't have backported it if it didn't at least work on your end, so I'm gonna trust you and chalk it up to me not having the right hardware. I couldn't reproduce the desired effect with official MouseTweaks 2.10.1 for 1.12 either.

> If you'd like, I can edit the README.md with info on the config options.

Would love that. There is so much stuff in the pack that isn't documented. At least making sure newly added things are documented somewhere should help.

**Comment by eigenraven** [comment]
@unilock Have you tested the Java 17 version too (runClient17)? It changes scrolling values compared to lwjgl2, I'm curious if the same bug with macos is present there too.

**Comment by unilock** [comment]
@eigenraven
With `runClient17`, `ScrollItemScaling=0` doesn't scroll items at all, while `ScrollItemScaling=1` scrolls an entire stack (one at a time, as if it's repeatedly moving 1 item, rather than instantly moving 64 items).

I'm guessing the "bug" would persist anyway, since I still need to set `ScrollItemScaling=1` even on Minecraft 1.20.1 / Mouse Tweaks 2.25.

(`runClient` crashes during startup, saying `./run/natives/lwjgl2/liblwjgl.dylib` is `missing compatible architecture (have 'x86_64', need 'arm64')`, I guess because the buildscript(?) uses Java 17 *arm64,* but Java 8 *x86_64.* Note that I'm using an arm64 machine.)

...and I didn't forget about updating the README; I've just been busy :P

**Comment by wlhlm** [comment]
> ...and I didn't forget about updating the README; I've just been busy :P

Don't worry, do it at your own pace. We always appreciate people taking the time to fix bugs or implement new features.

**Comment by unilock** [comment]
OK, the README has been updated :)

I wasn't sure how to describe `ScrollItemScaling`, as its behavior sort of conflicts with its own descriptions, so I just borrowed from [upstream's config screen](https://github.com/YaLTeR/MouseTweaks/blob/master/src/main/java/yalter/mousetweaks/ConfigScreen.java#L61).

**Comment by wlhlm** [comment]
> OK, the README has been updated :)

Wow, with screenshots even. Great job! Thank you.

I can't comment on the `runClient17` issues though. Maybe Raven knows more.

**Comment by wlhlm** [comment]
@unilock

> With runClient17, ScrollItemScaling=0 doesn't scroll items at all, while ScrollItemScaling=1 scrolls an entire stack (one at a time, as if it's repeatedly moving 1 item, rather than instantly moving 64 items).
> 
> I'm guessing the "bug" would persist anyway, since I still need to set ScrollItemScaling=1 even on Minecraft 1.20.1 / Mouse Tweaks 2.25.

Not sure if I understand you correctly, but are you saying that if `ScrollItemScaling` is set to 0 (which is the default), then item scrolling is broken completely on java17/lwjgl3? I don't think that's acceptable even if the same applies to upstream.

**Comment by unilock** [comment]
@wlhlm
> are you saying that if `ScrollItemScaling` is set to 0 (which is the default), then item scrolling is broken completely on java17/lwjgl3?

Yep!

> I don't think that's acceptable even if the same applies to upstream.

On upstream (MC 1.20.1 / MT 2.25), I get the same behavior when `ScrollItemScaling` is set to `0` as I do with this fork + Java 8: 3 items are moved per "mouse wheel notch" instead of 1. Setting the config option to `1` in both instances correctly moves just 1 item instead.

The "unacceptable behavior" only occurs when running this fork on Java 17.

Note that I can only set `ScrollItemScaling=1` with this PR, obviously, and that items not being moved at all when scrolling is a bug that also exists on the latest official release of this fork ([2.4.8-GTNH](https://github.com/GTNewHorizons/MouseTweaks/releases/tag/2.4.8-GTNH)).

**Comment by eigenraven** [comment]
When lwjgl3ify is present (you can check with Loader.isModLoaded), the wheel scroll events are scaled identically across all platforms so you shouldn't divide by 120, the value from the event is the number of "ticks" of the scrollwheel - see <https://github.com/GTNewHorizons/Galacticraft/pull/78/files> for an example patch. With lwjgl2, you need to divide by 120 on Windows, but other systems have different divisors (iirc 80 on linux and none on mac), that's why scrolling was broken on mac most likely.

**Comment by Dream-Master** [comment]
@unilock

**Comment by Dream-Master** [comment]
@unilock what is happend with this pr? Did it need changes ? A new review? Or should we close it?

**Comment by unilock** [comment]
> what is happend with this pr? Did it need changes ?

Sorry, I've been pretty busy ~~procrastinating~~.

My latest commit attempts to add support for LWJGL3. It does fix the issue where having `ScrollItemScaling=0` doesn't scroll items at all, but now, regardless of the setting, an entire stack of items is transferred at once instead of a single item (as would be expected). Note again that items are transferred one at a time, as if it's repeatedly moving 1 item, rather than instantly moving 64 items.

I'm not quite sure how to fix this yet.

Although, I did wonder at one point whether it would be worth it to just backport the majority of upstream, modern Mouse Tweaks specifically for LWJGL3? That would probably fix the issue, but would likely also be more trouble than it's worth...

**Comment by Dream-Master** [comment]
@unilock your decission. Let me know what we are doing.

**Comment by eigenraven** [comment]
I think this can probably be merged as-is as lwjgl3 handling at least works now, and a bigger refactor can become another PR.

**Comment by unilock** [comment]
Is LWJGL3 handling working correctly on non-macOS systems? That is, is only one item transferred per scroll wheel "tick", as opposed to the entire stack? (the latter being the behavior I'm seeing)

I do agree that a major refactor should be left for a separate PR, especially given my timeliness (or lack thereof), heh.

**Comment by Dream-Master** [comment]
@eigenraven then feel free to approve it :)

**Review by eigenraven — APPROVED** [review]

**Comment by unilock** [comment]
@eigenraven Were you able to test the latest commit with LWJGL3? It was *not* working properly on my end, but that may be a macOS-specific issue. (I don't have a non-macOS device to test on at the moment.)

**Comment by eigenraven** [comment]
Hmm it seems to continuously move items over until a mouse movement or ~50-64 items move on linux, it's broken after all

**Comment by eigenraven** [comment]
It look like you never pop the mouse wheel event from the queue when handling it

**Comment by eigenraven** [comment]
I found the cause, it's a bug in lwjgl3ify and not your code, I'll make an update to fix it

**Pull request merged**
